{
  "name": "qhub auto update",
  "on": {
    "push": {
      "branches": [
        "main"
      ],
      "paths": [
        "qhub-config.yaml"
      ]
    }
  },
  "env": {
    "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
    "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
    "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
    "AWS_DEFAULT_REGION": "${{ secrets.AWS_DEFAULT_REGION }}"
  },
  "jobs": {
    "build": {
      "name": "qhub",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout Image",
          "uses": "actions/checkout@master",
          "with": {
            "token": "${{ secrets.REPOSITORY_ACCESS_TOKEN }}"
          }
        },
        {
          "name": "Set up Python",
          "uses": "actions/setup-python@v2",
          "with": {
            "python-version": "3.10"
          }
        },
        {
          "name": "Install QHub",
          "run": "pip install qhub==0.4.5"
        },
        {
          "name": "Deploy Changes made in qhub-config.yaml",
          "run": "qhub deploy -c qhub-config.yaml --disable-prompt"
        },
        {
          "name": "Push Changes",
          "run": "git config user.email 'qhub@quansight.com' ; git config user.name 'github action' ; git add . ; git diff --quiet && git diff --staged --quiet || (git commit -m '${{ env.COMMIT_MSG }}') ; git push origin main",
          "env": {
            "COMMIT_MSG": "qhub-config.yaml automated commit: ${{ github.sha }}"
          }
        }
      ]
    }
  }
}